# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'AFNetworking', '0.9.1'
target 'project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for project

  target 'project-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'projectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'project-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for project-tvOS


end

